# Generated by Django 4.2.4 on 2023-09-04 10:37

import account.models.profile
import conf.time
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='post.category', verbose_name='دسته بندی')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_prescriptions', to='account.profile', validators=[account.models.profile.validate_is_not_trappist], verbose_name='مراجع')),
                ('trappist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trappist_prescriptions', to='account.profile', validators=[account.models.profile.validate_is_trappist], verbose_name='درمانگر')),
            ],
            options={
                'verbose_name': 'نسخه ها',
                'verbose_name_plural': 'نسحه',
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('dosage', models.FloatField(verbose_name='میزان دوز مصرفی')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('intake', models.TextField(verbose_name='نحوه مصرف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='prescription.prescription', verbose_name='نسخه')),
            ],
            options={
                'verbose_name': 'داروها',
                'verbose_name_plural': 'دارو',
                'db_table': 'drug',
            },
        ),
    ]
