# Generated by Django 3.2.20 on 2023-08-27 11:39

import conf.time
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('body', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل')),
                ('type', models.CharField(blank=True, choices=[], max_length=15, null=True, verbose_name='نوع')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='اولویت')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='امتیاز')),
            ],
            options={
                'verbose_name': 'پاسخ ها',
                'verbose_name_plural': 'پاسخ',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('body', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='قایل')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='اولویت')),
                ('type', models.CharField(blank=True, choices=[], max_length=15, null=True, verbose_name='نوع تست')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سوالات',
                'verbose_name_plural': 'سوال',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='الویت')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='زمان')),
                ('min_age', models.IntegerField(blank=True, null=True, verbose_name='حداقل سن')),
                ('max_age', models.IntegerField(blank=True, null=True, verbose_name='حداکثر سن')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('question_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد سوالات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='دسته بندی')),
                ('parent_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.test', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'تست ها',
                'verbose_name_plural': 'تست',
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='امتیاز')),
                ('start_time', models.IntegerField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_time', models.IntegerField(blank=True, null=True, verbose_name='زمان پایان')),
                ('is_valid', models.BooleanField(default=False, verbose_name='معتبر')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test', verbose_name='تست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.choiceuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تست های کاربران',
                'verbose_name_plural': 'تست کاربر',
                'db_table': 'user_test',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('body', models.TextField(blank=True, null=True, verbose_name='محتوا پاسخ')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='امتیاز')),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.answer', verbose_name='جواب کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='سوال')),
                ('user_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.usertest', verbose_name='تست کاربر')),
            ],
            options={
                'verbose_name': 'جواب کاربر',
                'verbose_name_plural': 'جواب کاربر',
                'db_table': 'user_answer',
            },
        ),
        migrations.CreateModel(
            name='TestPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('original_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت اصلی')),
                ('offer_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test', verbose_name='تست')),
            ],
            options={
                'verbose_name': 'قیمت تست ها',
                'verbose_name_plural': 'قیمت تست',
                'db_table': 'test_payment',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test', verbose_name='تست'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='سوال'),
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test', verbose_name='تست'),
        ),
    ]
