# Generated by Django 4.2.4 on 2023-09-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='الویت'),
        ),
    ]
