# Generated by Django 4.2.4 on 2023-09-19 12:57

import conf.time
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('exam', '0002_alter_test_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر')),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('like', models.BooleanField(blank=True, null=True, verbose_name='لایک')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='exam.test', verbose_name='پکیج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_retes', to='account.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز تست',
                'verbose_name_plural': 'امتیاز تست',
                'db_table': 'test_rate',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
