# Generated by Django 3.2.20 on 2023-08-31 07:00

import conf.model
import conf.time
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('color', models.TextField(blank=True, null=True, verbose_name='رنگ')),
                ('index', models.IntegerField(default=0, verbose_name='مرتب سازی بر اساس عدد - هرچه کوچکتر مقدم تر')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents_category', to='post.category', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('published_date', models.BigIntegerField(blank=True, null=True, verbose_name='رمان انتشار')),
                ('status', models.CharField(blank=True, choices=[('draft', 'پیش نویس'), ('published', 'منتشر شده')], max_length=20, null=True, verbose_name='وضعیت')),
                ('comment_status', models.CharField(blank=True, choices=[('open', 'باز'), ('closure', 'بسته')], max_length=20, null=True, verbose_name='وضعیت کامنت')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد بازدید کنندگان')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='account.profile', verbose_name='کاربر')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('is_valid', models.BooleanField(default=False, verbose_name='معتبر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='post.category', verbose_name='دسته بندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='account.profile', validators=[conf.model.validate_is_trappist], verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسته بندی کاربر',
                'verbose_name_plural': 'دسته بندی کاربر',
                'db_table': 'user_category',
            },
        ),
        migrations.CreateModel(
            name='TrappistCategoryPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('time', models.PositiveIntegerField(blank=True, null=True, verbose_name='رمان')),
                ('add_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='رمان_اضاقه')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('add_price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت_اضاقه')),
                ('is_valid', models.BooleanField(default=False, verbose_name='معتبر')),
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_price', to='post.usercategory')),
            ],
            options={
                'verbose_name': 'قیمت تخصص درمانگر',
                'verbose_name_plural': 'قیمت تخصص درمانگر',
                'db_table': 'trappist_category_price',
            },
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('file', models.FileField(blank=True, null=True, upload_to='post_files', verbose_name='فایل')),
                ('is_main', models.BooleanField(default=False, verbose_name='فایل اصلی')),
                ('is_valid', models.BooleanField(default=True, verbose_name='معتبر')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='ترتیب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='post.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'فایل های پست',
                'verbose_name_plural': 'فایل های پست',
                'db_table': 'post_file',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='post.Tag', verbose_name='تگ ها'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('body', models.TextField(max_length=300, verbose_name='محتوا')),
                ('is_enable', models.BooleanField(default=False, verbose_name='فعال')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents_comment', to='post.comment', verbose_name='کامنت پدر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='account.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='PostRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('like', models.BooleanField(blank=True, null=True, verbose_name='لایک')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='post.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_retes', to='account.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز پست',
                'verbose_name_plural': 'امتیاز پست',
                'db_table': 'post_rate',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
