# Generated by Django 4.2.4 on 2023-09-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='index',
            field=models.IntegerField(default=0, verbose_name='مرتب سازی بر اساس عدد - هرچه کوچکتر مقدم تر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
