# Generated by Django 3.2.20 on 2023-08-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'دسته بندی کاربر', 'verbose_name_plural': 'دسته بندی کاربر'},
        ),
        migrations.AlterModelTable(
            name='usercategory',
            table='user_category',
        ),
    ]
