# Generated by Django 4.2.4 on 2023-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_index_alter_comment_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مدت زمان مطالعه'),
        ),
    ]
