# Generated by Django 3.2.20 on 2023-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20230824_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='post.Tag', verbose_name='تگ ها'),
        ),
    ]
