# Generated by Django 3.2.20 on 2023-08-27 11:39

import conf.time
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('site_name', models.CharField(default='', max_length=200, verbose_name='نام سایت')),
                ('site_description', models.TextField(default='', max_length=1000, verbose_name='توضیحات سایت')),
                ('site_seo_description', models.TextField(default='', max_length=1000, verbose_name='توضیحات سئوی سایت')),
                ('site_keywords', models.TextField(default='', max_length=1000, verbose_name='کلمات کلیدی وب سایت')),
                ('global_header', models.TextField(blank=True, default='', null=True, verbose_name='هدر سایت')),
                ('global_footer', models.TextField(blank=True, default='', null=True, verbose_name='فوتر سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
                'db_table': 'site_setting',
            },
        ),
    ]
