# Generated by Django 3.2.20 on 2023-08-31 07:00

import conf.time
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='اولویت')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='ترتیب')),
                ('summary', models.CharField(blank=True, max_length=250, null=True, verbose_name='خلاصه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('prerequisite', models.TextField(blank=True, null=True, verbose_name='پیش نیاز')),
                ('time', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان دوره')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد بازدید کنندگان')),
                ('sell_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش دوزه')),
                ('category', models.ManyToManyField(related_name='packages', to='post.UserCategory', verbose_name='دسته بندی کاربر')),
                ('parent_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents_package', to='package.package', verbose_name='پکیج پدر')),
                ('tags', models.ManyToManyField(related_name='package', to='post.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'پکیج ها',
                'verbose_name_plural': 'پکیج',
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('is_payed', models.BooleanField(default=True, verbose_name='پرداخت شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_package', to='package.package', verbose_name='پکیج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='account.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پکیج های کاربر',
                'verbose_name_plural': 'پکیج های کاربر',
                'db_table': 'user_package',
            },
        ),
        migrations.CreateModel(
            name='PackagePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('original_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت اصلی')),
                ('offer_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='package.package', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'قیمت پکیج',
                'verbose_name_plural': 'قیمت پکیج',
                'db_table': 'package_payment',
            },
        ),
        migrations.CreateModel(
            name='PackageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('file', models.FileField(blank=True, null=True, upload_to='package_files', verbose_name='فایل')),
                ('is_main', models.BooleanField(default=False, verbose_name='فایل اصلی')),
                ('is_valid', models.BooleanField(default=True, verbose_name='معتبر')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='ترتیب')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='package.package', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'فایل های پکیج',
                'verbose_name_plural': 'فایل های پکیج',
                'db_table': 'package_file',
            },
        ),
        migrations.CreateModel(
            name='PackageRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر')),
                ('rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('like', models.BooleanField(blank=True, null=True, verbose_name='لایک')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='package.package', verbose_name='پکیج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_retes', to='account.profile', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز پکیج',
                'verbose_name_plural': 'امتیاز پکیج',
                'db_table': 'package_rate',
                'unique_together': {('user', 'package')},
            },
        ),
    ]
