# Generated by Django 4.2.4 on 2023-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('package', '0003_alter_package_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ManyToManyField(related_name='packages', to='post.category', verbose_name='دسته بندی کاربر'),
        ),
    ]
