# Generated by Django 4.2.4 on 2023-09-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('post', '0001_initial'),
        ('package', '0004_alter_package_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='account.profile', verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ManyToManyField(related_name='packages', to='post.category', verbose_name='دسته بندی'),
        ),
        migrations.DeleteModel(
            name='UserPackage',
        ),
    ]
