# Generated by Django 4.2.4 on 2023-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_alter_package_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='time',
            field=models.PositiveIntegerField(default=0, verbose_name='مدت زمان دوره'),
        ),
    ]
