# Generated by Django 4.2.4 on 2023-09-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_time_to_read'),
        ('package', '0007_alter_package_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='packages', to='post.category', verbose_name='دسته بندی'),
        ),
    ]
