# Generated by Django 3.2.20 on 2023-08-31 07:00

import conf.model
import conf.time
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='تلفن همراه')),
                ('is_verified', models.BooleanField(default=False, verbose_name='فعال')),
                ('nationality_code', models.IntegerField(blank=True, null=True, verbose_name='کد ملی')),
                ('type', models.CharField(choices=[('client', 'مراحع'), ('trappist', 'درمانگر')], max_length=20, verbose_name='نوع کاربر')),
                ('date_of_birth', models.BigIntegerField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('unknown', 'نامشخص')], max_length=10, null=True, verbose_name='جنسیت')),
                ('user_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد معرفی')),
                ('invitor_code', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='کد معرف')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('file', models.FileField(blank=True, null=True, upload_to='document_files', verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدرک',
                'db_table': 'document_field',
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مدارک پزشکی',
                'verbose_name_plural': 'مدارک پزشکی',
                'db_table': 'medical_document',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationFields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('test_status', models.CharField(blank=True, choices=[('bought', 'خریداری شده'), ('done', 'انجام شده'), ('get_result', 'دریافت نتیجه')], max_length=40, null=True, verbose_name='وضعیت تست')),
                ('counseling_status', models.CharField(blank=True, choices=[('b', 'a'), ('d', 'c')], max_length=40, null=True, verbose_name='وضعیت جلسه مشاوره')),
                ('post_status', models.CharField(blank=True, choices=[('creation', 'ساخته شده'), ('published', 'منتشر شده'), ('deleted', 'حذف شده'), ('get_comment', 'دریافت کامنت'), ('get_like', 'دریافت لایک'), ('get_dislike', 'دریافت دیسلاک')], max_length=40, null=True, verbose_name='وضعیت پست')),
                ('off_code_status', models.CharField(blank=True, choices=[('test', 'تست'), ('package', 'پکیج'), ('counseling', 'مشاوره')], max_length=40, null=True, verbose_name='وضعیت کد تخفیف')),
            ],
            options={
                'verbose_name': 'اعلان ها',
                'verbose_name_plural': 'اعلان ها',
                'db_table': 'notification_fields',
            },
        ),
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('code', models.CharField(editable=False, max_length=6, verbose_name='کد')),
                ('expire_date', models.BigIntegerField(verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تایید',
                'verbose_name_plural': 'کدهای تایید',
                'db_table': 'phone_code',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('is_trappist', models.BooleanField(default=False, verbose_name='درمانگر')),
                ('first_name', models.CharField(max_length=40, verbose_name='نام')),
                ('last_name', models.CharField(max_length=40, verbose_name='نام خانوادگی')),
                ('specialized_field', models.CharField(blank=True, max_length=50, null=True, verbose_name='رشته تخصصی')),
                ('system_code', models.IntegerField(blank=True, null=True, verbose_name='کد نظام')),
                ('level', models.CharField(blank=True, choices=[('bachelors', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('doctor', 'دکترا')], max_length=20, null=True, verbose_name='سطخ تحصیلات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='تصویر')),
                ('file', models.FileField(blank=True, null=True, upload_to='profile_files', verbose_name='فایل')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='درباره من')),
                ('sheba', models.CharField(blank=True, max_length=24, null=True, verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('bank_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام بانک')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='SpecializedDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مدارک تخصصی',
                'verbose_name_plural': 'مدارک تخصصی',
                'db_table': 'specialized_document',
            },
        ),
        migrations.CreateModel(
            name='TrappistRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('rate', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز درمانگر')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر')),
                ('is_valid', models.BooleanField(default=True, verbose_name='معتبر')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rate', to='account.profile', validators=[conf.model.validate_is_not_trappist], verbose_name='مراجع')),
                ('trappist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trappist_rate', to='account.profile', validators=[conf.model.validate_is_trappist], verbose_name='درمانگر')),
            ],
            options={
                'verbose_name': 'امتیاز درمانگر',
                'verbose_name_plural': 'امتیاز درمانگر',
                'db_table': 'trappist_rate',
            },
        ),
    ]
