# Generated by Django 3.2.20 on 2023-08-27 11:40

import conf.time
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.usercategory', verbose_name='دسته بندی کاربر')),
            ],
            options={
                'verbose_name': 'مدارک',
                'verbose_name_plural': 'مدارک',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.document', verbose_name='')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدرک',
                'db_table': 'document_field',
            },
        ),
    ]
