# Generated by Django 3.2.20 on 2023-09-02 10:07

import account.models.profile
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exam', '0001_initial'),
        ('account', '0001_initial'),
        ('package', '0001_initial'),
        ('payment', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializeddocuments',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='post.usercategory', verbose_name='دسته بندی کاربر'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='notificationfields',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='account.notification', verbose_name='اعلان'),
        ),
        migrations.AddField(
            model_name='notificationfields',
            name='off_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payment.offcode', verbose_name='تخفیف خرید'),
        ),
        migrations.AddField(
            model_name='notificationfields',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='post.post', verbose_name='پست'),
        ),
        migrations.AddField(
            model_name='notificationfields',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='exam.test', verbose_name='تست'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.profile', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='account.profile', validators=[account.models.profile.validate_is_not_trappist], verbose_name='مراجع'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to='package.package', verbose_name='پکیج'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to='post.post', verbose_name='پست'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='account.profile', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to='exam.test', verbose_name='تست'),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='medical_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='account.medicaldocument', verbose_name='مدارک پزشکی'),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='specialized_documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='account.specializeddocuments', verbose_name='مدارک تخصصی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
