# Generated by Django 3.2.20 on 2023-09-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nationality_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='شهر'),
        ),
    ]
