# Generated by Django 3.2.20 on 2023-08-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecode',
            options={'ordering': ('create_date',), 'verbose_name': 'کد تایید', 'verbose_name_plural': 'کدهای تایید'},
        ),
    ]
