# Generated by Django 3.2.20 on 2023-08-31 12:00

import conf.time
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
        ('post', '0001_initial'),
        ('exam', '0001_initial'),
        ('account', '0003_alter_phonecode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('client', 'مراحع'), ('trappist', 'درمانگر')], max_length=20, null=True, verbose_name='نوع کاربر'),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='شناسه')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='حذف شده')),
                ('create_date', models.BigIntegerField(default=conf.time.time_now, editable=False, verbose_name='تاریخ ایجاد')),
                ('update_date', models.BigIntegerField(default=conf.time.time_now, verbose_name='تاریخ ویرایش')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to='package.package', verbose_name='پکیج')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to='post.post', verbose_name='پست')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='account.profile', verbose_name='کاربر')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to='exam.test', verbose_name='تست')),
            ],
            options={
                'verbose_name': 'پسندیده ها',
                'verbose_name_plural': 'پسندیده ها',
                'db_table': 'favourite',
            },
        ),
    ]
