# Generated by Django 3.2.20 on 2023-09-03 12:42

import account.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230903_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[account.models.profile.validate_iranian_national_code], verbose_name='کد ملی'),
        ),
    ]
