# Generated by Django 3.2.20 on 2023-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_nationality_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='license_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره پروانه اشتغال'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد نظام'),
        ),
    ]
