# Generated by Django 3.2.20 on 2023-09-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20230904_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='معتبر'),
        ),
    ]
