# Generated by Django 4.2.4 on 2023-09-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_is_valid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user', violation_error_message='کاربر با این مشخصات قبلا ثبت شده است'),
        ),
    ]
